kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"

    #The docs specify that you should SSH into the node and create a data directory under /mnt but we could similarly just specify /mnt or as another student mentioned /tmp as the hostPath