# this does fibonnaci calculation and this is absolutely the slowest part of our application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'


# here multi-worker is going to make request to cluster ip of redis pod but no one is going to make request to multi-worker so we dint need to open up any port in multiworker
# as we only need to assign  port if request is going inside the pod 